language: node_js
node_js:
- '6'
- '7'
- '10'
branches:
  only:
  - master
  - develop
  - /^v?(\\d\\.){2}\\d$/
  - /^greenkeeper-.*$/
  - /^greenkeeper/.*$/
notifications:
  email:
  - nfantone@gmail.com
cache:
  bundler: true
  directories:
  - node_modules
script: npm run validate && npm run coverage
deploy:
  provider: npm
  email: nfantone@gmail.com
  api_key:
    secure: EAGwUxXIc9iJq5xymmSW1QSj6/kUXmjmBxvaSNIBQHPK9q+meXTth8reDql7x96NVE0rtCVPj6Vv9LPha9TojOUgrjgc0/UdX3xG7Y+2omSQeU6KnbhWm17H1cO4AS4wN9GZMtIC97QLSiL6fIVWMHWTIMoyPfMn/R50icRatpp7eCyfyzUV7Q/sqtEzgqXL6ETz1AlJKEb2oH0b0n4Am0ICjv1/Uo75KqgmPx3fPpAsAB2ZOR2509NdORPMOGDfL/wNn1Kn1xLiC2kdnNLsVn4GNHi516vX44mx5B6Lwcak709YGmRJmwFzYr0Q14BAHBL49AxmibZOSlWFtDPfWzY4Gie0CjdNEvESernSg3HhN6TdG29G3esBOCNdomSFeUdvvir8HyKn0CsFwTpY8BHqKSev+U+am3ehIkIYgAPNROJl8g8+tMk4ELulMMKM3GQk6qUvU1nOG0cl+cntuEscF5WIR8qEdDi+AYDAw9YwhXFR5LJ9ge3en9mqFecl4zj9KmdyoiENfWZXQ88xtVvBQLURxU5kPrWUBIJcg84q35Qeex5rWLgNM9ITFWdd/WMjq/ub3+06ZjiFl3IHVKrjmFhhtlvAVPg/ISONR0PIYFHHagbV83S0gizAE+Yivs/fWQBhW1xHX6FYAJQSERFNJm3C2itRwXngNNS3dLI=
  on:
    tags: true
    repo: nfantone/mu-koan-generator
    node_js: '7'
